# Generated by Django 3.2.2 on 2022-10-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('passport_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='passport_id')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('surname', models.CharField(max_length=150, verbose_name='surname')),
                ('patronymic', models.CharField(max_length=150, verbose_name='patronymic')),
                ('registration', models.CharField(max_length=150, verbose_name='registration')),
                ('children_number', models.IntegerField(verbose_name='children_number')),
                ('is_married_now', models.BooleanField(verbose_name='is_married_now')),
                ('birth_date', models.DateField(verbose_name='birth_date')),
                ('is_depth', models.BooleanField(verbose_name='is_depth')),
                ('depth_date', models.DateField(verbose_name='depth_date')),
            ],
            options={
                'db_table': 'passports',
            },
        ),
    ]
