# Generated by Django 3.2.2 on 2022-10-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20221016_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='acs_lvl',
        ),
        migrations.AddField(
            model_name='user',
            name='acs_level',
            field=models.IntegerField(default=None, verbose_name='acs_level'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
